version: "3"

services:
  integration:
    build: ./
    networks:
      - integration

  vote:
    build: ../
    environment:
      - PORT=80 # By default vote listens on 5000, override
    depends_on:
      - redis
    networks:
      - integration

  redis:
    image: redis:alpine
    networks:
      - integration

networks:
  integration:
